version: '3.9'

services:
  db:
    image: postgres:16
    container_name: nuxt_postgres
    restart: always
    environment:
      POSTGRES_USER: azidav
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: solverdept_db_2025
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
